using System.Text.Json.Nodes;
using System.Text.RegularExpressions;
using Npgsql;

namespace Andrade;
public record RequestInput(string Name, string Email, string Phone, string ServiceId, string Message, string Mode, string? AppointmentAt, bool Consent, string IdempotencyKey, string TrackingToken, string? Website = null);
public sealed class Portal(Database db)
{
    public static readonly string[] Statuses = ["recibido", "revision", "confirmado", "completado", "cancelado"];
    public Task<JsonNode?> Settings() => db.Json("SELECT data FROM andrade_portal.settings WHERE id=true");
    public Task<JsonNode?> Content(string kind, bool admin = false) => db.Json("SELECT COALESCE(jsonb_agg(data || jsonb_build_object('id',id,'active',active,'sortOrder',sort_order,'createdAt',created_at) ORDER BY sort_order,id),'[]'::jsonb) FROM andrade_portal.content WHERE kind=@kind AND (@admin OR active)", ("kind", kind), ("admin", admin));
    public async Task<object> Public() => new { settings = await Settings(), services = await Content("services"), promotions = await Content("promotions") };
    public async Task<object> Posts(int offset = 0, int limit = 6, string? category = null, string? search = null) { offset = Math.Clamp(offset, 0, 100000); limit = Math.Clamp(limit, 1, 12); var all = await db.Json("SELECT COALESCE(jsonb_agg(row),'[]'::jsonb) FROM (SELECT data || jsonb_build_object('id',id,'createdAt',created_at) AS row FROM andrade_portal.content WHERE kind='posts' AND active AND (@category='' OR data->>'category'=@category) AND (@q='' OR data->>'title' ILIKE @pattern OR data->>'summary' ILIKE @pattern) ORDER BY sort_order,id LIMIT @limit OFFSET @offset) x", ("category", category ?? ""), ("q", search ?? ""), ("pattern", "%" + (search ?? "").Replace("%", "\\%").Replace("_", "\\_") + "%"), ("limit", limit + 1), ("offset", offset)); var items = all!.AsArray(); var more = items.Count > limit; if (more) items.RemoveAt(items.Count - 1); return new { items, hasMore = more, nextOffset = offset + items.Count }; }
    public async Task<string[]> Slots(string date)
    {
        if (!DateOnly.TryParseExact(date, "yyyy-MM-dd", out var day)) throw new PortalException("Elige una fecha válida."); var now = DateTimeOffset.UtcNow.ToOffset(TimeSpan.FromHours(-5)); if (day < DateOnly.FromDateTime(now.Date) || day > DateOnly.FromDateTime(now.Date).AddDays(60)) return [];
        var s = (await Settings())!; var weekdays = s["weekdays"]!.AsArray().Select(v => v!.GetValue<int>()); if (!weekdays.Contains((int)day.DayOfWeek) || s["closedDates"]!.AsArray().Any(d => d!.ToString() == date)) return [];
        var booked = (await db.Json("SELECT COALESCE(jsonb_agg(to_char(appointment_at AT TIME ZONE 'America/Guayaquil','YYYY-MM-DD HH24:MI')),'[]'::jsonb) FROM andrade_portal.requests WHERE appointment_at IS NOT NULL AND status NOT IN ('cancelado','completado') AND (appointment_at AT TIME ZONE 'America/Guayaquil')::date=@date::date", ("date", date)))!.AsArray().Select(d => d!.ToString()).ToHashSet();
        return Enumerable.Range(s["startHour"]!.GetValue<int>(), s["endHour"]!.GetValue<int>() - s["startHour"]!.GetValue<int>()).Select(h => $"{date}T{h:00}:00:00-05:00").Where(v => DateTimeOffset.Parse(v) > now.AddHours(1) && !booked.Contains(v[..10] + " " + v.Substring(11, 5))).ToArray();
    }
    public async Task<object> CreateRequest(RequestInput input)
    {
        if (!string.IsNullOrWhiteSpace(input.Website)) throw new PortalException("Solicitud no válida.");
        Validate.Text(input.Name, 2, 100, "nombre"); Validate.Text(input.Phone, 7, 25, "teléfono"); if (!Regex.IsMatch(input.Phone, @"^\+?[\d\s()\-]{7,25}$")) throw new PortalException("Revisa tu teléfono.");
        if (!string.IsNullOrWhiteSpace(input.Email) && !System.Net.Mail.MailAddress.TryCreate(input.Email, out _)) throw new PortalException("Revisa tu correo electrónico."); if (input.Email.Length > 200) throw new PortalException("El correo es demasiado largo.");
        Validate.Text(input.Message, 10, 3000, "resumen"); if (!input.Consent) throw new PortalException("Debes aceptar el tratamiento de datos para enviar la solicitud."); if (!new[] { "presencial", "virtual" }.Contains(input.Mode)) throw new PortalException("Selecciona una modalidad válida.");
        if (!Guid.TryParse(input.IdempotencyKey, out var idem) || !Regex.IsMatch(input.TrackingToken ?? "", @"^[a-f0-9]{64}$")) throw new PortalException("Recarga el formulario antes de enviar.");
        var trackingHash = Auth.Hash(input.TrackingToken!);
        var previous = await db.Json("SELECT jsonb_build_object('reference',reference,'status',status,'appointmentAt',appointment_at) FROM andrade_portal.requests WHERE idempotency_key=@key AND tracking_hash=@hash", ("key", idem), ("hash", trackingHash)); if (previous != null) return previous;
        if (input.ServiceId != "general" && (await Content("services"))!.AsArray().All(s => s!["id"]!.ToString() != input.ServiceId)) throw new PortalException("Selecciona un servicio disponible.");
        DateTimeOffset? appointment = null; if (!string.IsNullOrWhiteSpace(input.AppointmentAt)) { if (!DateTimeOffset.TryParse(input.AppointmentAt, out var parsed)) throw new PortalException("Horario no válido."); appointment = parsed.ToUniversalTime(); var date = parsed.ToOffset(TimeSpan.FromHours(-5)).ToString("yyyy-MM-dd"); if (!(await Slots(date)).Any(slot => DateTimeOffset.Parse(slot) == parsed)) throw new PortalException("Este horario ya no está disponible. Elige otro.", 409); }
        var id = Guid.NewGuid(); var reference = "AA-" + Convert.ToHexString(System.Security.Cryptography.RandomNumberGenerator.GetBytes(6));
        await using var c = await db.Source.OpenConnectionAsync(); await using var tx = await c.BeginTransactionAsync(); try
        {
            await using (var cmd = Database.Command(c, "INSERT INTO andrade_portal.requests(id,reference,tracking_hash,idempotency_key,name,email,phone,service_id,message,mode,appointment_at) VALUES(@id,@ref,@hash,@key,@name,@email,@phone,@service,@message,@mode,@at)", ("id", id), ("ref", reference), ("hash", trackingHash), ("key", idem), ("name", input.Name.Trim()), ("email", input.Email.Trim()), ("phone", input.Phone.Trim()), ("service", input.ServiceId), ("message", input.Message.Trim()), ("mode", input.Mode), ("at", appointment))) { await cmd.ExecuteNonQueryAsync(); }
            await using (var cmd = Database.Command(c, "INSERT INTO andrade_portal.request_events(request_id,status,note) VALUES(@id,'recibido','Solicitud recibida. El despacho revisará los datos y confirmará los siguientes pasos.')", ("id", id))) { await cmd.ExecuteNonQueryAsync(); }
            await tx.CommitAsync();
        }
        catch (PostgresException ex) when (ex.SqlState == "23505") { throw new PortalException("El horario acaba de ocuparse o la solicitud ya se envió. Consulta tu seguimiento o elige otro horario.", 409); }
        return new { reference, status = "recibido", appointmentAt = appointment };
    }
    public async Task<JsonNode> Track(string reference, string token)
    {
        if (!Regex.IsMatch(reference ?? "", @"^AA-[A-F0-9]{12}$") || !Regex.IsMatch(token ?? "", @"^[a-f0-9]{64}$")) throw new PortalException("Código o clave de seguimiento incorrectos.", 404);
        return await db.Json("SELECT jsonb_build_object('reference',r.reference,'status',r.status,'serviceId',r.service_id,'mode',r.mode,'appointmentAt',r.appointment_at,'publicNote',r.public_note,'createdAt',r.created_at,'updatedAt',r.updated_at,'events',COALESCE((SELECT jsonb_agg(jsonb_build_object('status',e.status,'note',e.note,'createdAt',e.created_at) ORDER BY e.id) FROM andrade_portal.request_events e WHERE e.request_id=r.id),'[]'::jsonb)) FROM andrade_portal.requests r WHERE reference=@ref AND tracking_hash=@hash", ("ref", reference), ("hash", Auth.Hash(token!))) ?? throw new PortalException("Código o clave de seguimiento incorrectos.", 404);
    }
    public async Task Cancel(string reference, string token) { await Track(reference, token); await using var c = await db.Source.OpenConnectionAsync(); await using var tx = await c.BeginTransactionAsync(); await using var cmd = Database.Command(c, "UPDATE andrade_portal.requests SET status='cancelado',updated_at=now(),public_note='Solicitud cancelada por el cliente.' WHERE reference=@ref AND tracking_hash=@hash AND status NOT IN ('completado','cancelado') RETURNING id", ("ref", reference), ("hash", Auth.Hash(token))); var id = await cmd.ExecuteScalarAsync(); if (id == null) throw new PortalException("Esta solicitud ya está cerrada.", 409); await using var evt = Database.Command(c, "INSERT INTO andrade_portal.request_events(request_id,status,note) VALUES(@id,'cancelado','Solicitud cancelada por el cliente.')", ("id", id)); await evt.ExecuteNonQueryAsync(); await tx.CommitAsync(); }
    public Task<JsonNode?> Requests() => db.Json("SELECT COALESCE(jsonb_agg(row ORDER BY row->>'createdAt' DESC),'[]'::jsonb) FROM (SELECT jsonb_build_object('id',id,'reference',reference,'name',name,'email',email,'phone',phone,'serviceId',service_id,'message',message,'mode',mode,'appointmentAt',appointment_at,'status',status,'publicNote',public_note,'privateNote',private_note,'createdAt',created_at,'updatedAt',updated_at) row FROM andrade_portal.requests ORDER BY created_at DESC LIMIT 500) x");
    public async Task UpdateRequest(Guid id, JsonObject body) { var status = body["status"]?.ToString() ?? ""; if (!Statuses.Contains(status)) throw new PortalException("Estado no válido."); var note = body["publicNote"]?.ToString() ?? ""; var privateNote = body["privateNote"]?.ToString() ?? ""; if (note.Length > 2000 || privateNote.Length > 4000) throw new PortalException("La nota es demasiado larga."); await using var c = await db.Source.OpenConnectionAsync(); await using var tx = await c.BeginTransactionAsync(); await using (var cmd = Database.Command(c, "UPDATE andrade_portal.requests SET status=@status,public_note=@note,private_note=@private,updated_at=now() WHERE id=@id", ("status", status), ("note", note), ("private", privateNote), ("id", id))) { if (await cmd.ExecuteNonQueryAsync() == 0) throw new PortalException("Solicitud no encontrada.", 404); } await using (var cmd = Database.Command(c, "INSERT INTO andrade_portal.request_events(request_id,status,note) VALUES(@id,@status,@note)", ("id", id), ("status", status), ("note", note))) { await cmd.ExecuteNonQueryAsync(); } await tx.CommitAsync(); }
}
public sealed class PortalException(string message, int status = 400) : Exception(message) { public int Status { get; } = status; }
public static class Validate
{
    public static void Text(string? s, int min, int max, string name) { if (s == null || s.Trim().Length < min || s.Length > max) throw new PortalException($"Revisa el campo {name} ({min}–{max} caracteres)."); }
    public static bool MediaUrl(string? url) => string.IsNullOrEmpty(url) || Regex.IsMatch(url, @"^/images/[a-zA-Z0-9._-]+$") || Regex.IsMatch(url, @"^/api/media/[a-fA-F0-9-]{36}$");
    public static bool SocialUrl(string? raw) { if (string.IsNullOrEmpty(raw)) return true; if (!Uri.TryCreate(raw, UriKind.Absolute, out var u) || u.Scheme != "https") return false; return new[] { "www.instagram.com", "instagram.com", "www.youtube.com", "youtube.com", "youtu.be", "www.tiktok.com", "tiktok.com", "www.linkedin.com", "linkedin.com", "ec.linkedin.com" }.Contains(u.Host); }
    public static void Content(string kind, JsonObject data) { Text(data["title"]?.ToString(), 3, 160, "título"); Text(data["summary"]?.ToString(), 5, 400, "resumen"); if ((data["description"]?.ToString().Length ?? 0) > 20000) throw new PortalException("Descripción demasiado larga."); if (!MediaUrl(data["cover"]?.ToString())) throw new PortalException("Sube una imagen desde la biblioteca."); if (kind == "posts") { var type = data["kind"]?.ToString(); if (!new[] { "article", "instagram", "youtube", "tiktok", "linkedin", "video" }.Contains(type)) throw new PortalException("Tipo de publicación no válido."); var url = data["url"]?.ToString(); if (type != "article" && string.IsNullOrWhiteSpace(url)) throw new PortalException("Indica la URL del video o sube un archivo."); if (type == "video" && !Regex.IsMatch(url ?? "", @"^/api/media/[a-fA-F0-9-]{36}$")) throw new PortalException("Selecciona un video de la biblioteca."); if (type != "article" && type != "video" && !SocialUrl(url)) throw new PortalException("Utiliza una URL HTTPS de una red social compatible."); } }
}
