CREATE SCHEMA IF NOT EXISTS andrade_portal;
REVOKE ALL ON SCHEMA andrade_portal FROM PUBLIC, anon, authenticated;
CREATE TABLE IF NOT EXISTS andrade_portal.schema_migrations (version text PRIMARY KEY, checksum text NOT NULL, applied_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE andrade_portal.settings (id boolean PRIMARY KEY DEFAULT true CHECK(id), data jsonb NOT NULL, updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE andrade_portal.content (id text PRIMARY KEY, kind text NOT NULL CHECK(kind IN ('services','posts','promotions')), data jsonb NOT NULL, active boolean NOT NULL DEFAULT false, sort_order integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX content_feed ON andrade_portal.content(kind, active, sort_order, id);
CREATE TABLE andrade_portal.admin_users (id uuid PRIMARY KEY, email text UNIQUE NOT NULL, password_hash text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE andrade_portal.sessions (token_hash text PRIMARY KEY, user_id uuid NOT NULL REFERENCES andrade_portal.admin_users(id) ON DELETE CASCADE, expires_at timestamptz NOT NULL);
CREATE TABLE andrade_portal.requests (id uuid PRIMARY KEY, reference text UNIQUE NOT NULL, tracking_hash text NOT NULL, idempotency_key uuid UNIQUE NOT NULL, name text NOT NULL, email text NOT NULL DEFAULT '', phone text NOT NULL, service_id text NOT NULL, message text NOT NULL, mode text NOT NULL CHECK(mode IN ('presencial','virtual')), appointment_at timestamptz, status text NOT NULL DEFAULT 'recibido' CHECK(status IN ('recibido','revision','confirmado','completado','cancelado')), public_note text NOT NULL DEFAULT '', private_note text NOT NULL DEFAULT '', consent_at timestamptz NOT NULL DEFAULT now(), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX one_booking_per_slot ON andrade_portal.requests(appointment_at) WHERE appointment_at IS NOT NULL AND status NOT IN ('cancelado','completado');
CREATE INDEX requests_created ON andrade_portal.requests(created_at DESC);
CREATE TABLE andrade_portal.request_events (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, request_id uuid NOT NULL REFERENCES andrade_portal.requests(id) ON DELETE CASCADE, status text NOT NULL, note text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE andrade_portal.media (id uuid PRIMARY KEY, name text NOT NULL, content_type text NOT NULL, bytes bytea NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE andrade_portal.audit_log (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, actor text NOT NULL, action text NOT NULL, target text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE andrade_portal.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE andrade_portal.content ENABLE ROW LEVEL SECURITY;
ALTER TABLE andrade_portal.admin_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE andrade_portal.sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE andrade_portal.requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE andrade_portal.request_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE andrade_portal.media ENABLE ROW LEVEL SECURITY;
ALTER TABLE andrade_portal.audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE andrade_portal.schema_migrations ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON ALL TABLES IN SCHEMA andrade_portal FROM PUBLIC, anon, authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA andrade_portal FROM PUBLIC, anon, authenticated;
